apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: image
global:
  registry: LOCAL_REGISTRY

charts:
- name: istiod
  override:
    hub: $(registry)/istio/pilot
    tag: 1.13.1

- name: istio-ingress-gateway
  override:
    hub: $(registry)/istio/proxyv2
    tag: 1.13.1

- name: jaeger-operator
  override:
    image.repository: $(registry)/jaegertracing/jaeger-operator
    image.tag: 1.29.1
    collectorImage.repository: $(registry)/jaegertracing/jaeger-collector
    collectorImage.tag: 1.29.1
    agentImage.repository: $(registry)/jaegertracing/jaeger-agent
    agentImage.tag: 1.29.1
    ingesterImage.repository: $(registry)/jaegertracing/jaeger-ingester
    ingesterImage.tag: 1.29.1
    queryImage.repository: $(registry)/jaegertracing/jaeger-collector
    queryImage.tag: 1.29.1

- name: kiali-operator
  override:
    image.repo: $(registry)/kiali/kiali-operator
    image.tag: v1.45.1


