apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
spec:
  template:
    spec:
      containers:
      - name: cert-manager
        image: my-domain.io/jetstack/cert-manager-webhook:v1.5.0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: aiserving
                operator: In
                values:
                - enabled
